export const PATHFINDER_2E_SYSTEM = 'PATHFINDER_2E' as const
export const PATHFINDER_2E_DATA_KEY = 'pathfinder2e' as const
export const PATHFINDER_2E_SHEET_VERSION = 1

export const PROFICIENCY_RANKS = {
  UNTRAINED: 0,
  TRAINED: 2,
  EXPERT: 4,
  MASTER: 6,
  LEGENDARY: 8,
} as const

export const PROFICIENCY_RANK_VALUES = [
  PROFICIENCY_RANKS.UNTRAINED,
  PROFICIENCY_RANKS.TRAINED,
  PROFICIENCY_RANKS.EXPERT,
  PROFICIENCY_RANKS.MASTER,
  PROFICIENCY_RANKS.LEGENDARY,
] as const
