import type { Pathfinder2eOriginalContentRecord } from '../../records'
import type { Pathfinder2eSpellData } from '../types'

export const PATHFINDER_PLAYER_CORE_SPELL_ORIGINALS: readonly Pathfinder2eOriginalContentRecord<Pathfinder2eSpellData>[] = [
  {
    contentId: 'pf2e:spell:spells-srd:electric-arc',
    domain: 'SPELL',
    locale: 'en-US',
    sourceHash: 'git-blob:a6c45ae8e1dd8cf140d9c1396494dbd8b26e82d1',
    translatableHash: 'git-blob:a6c45ae8e1dd8cf140d9c1396494dbd8b26e82d1',
    source: { sourcePack: 'spells-srd', sourceId: 'kBhaPuzLUSwS6vVf', slug: 'electric-arc', publicationTitle: 'Pathfinder Player Core', license: 'ORC', remaster: true },
    data: {
      schemaVersion: 1,
      name: 'Electric Arc',
      rank: 1,
      rarity: 'common',
      traits: ['cantrip', 'concentrate', 'electricity', 'manipulate'],
      traditions: ['arcane', 'primal'],
      description: 'An arc of lightning leaps from one target to another. Each target takes 2d4 electricity damage with a basic Reflex save.',
      castingTime: '2 actions',
      range: '30 feet',
      target: '1 or 2 creatures',
      area: null,
      duration: 'instantaneous',
      defense: 'basic Reflex save',
      damage: [{ formula: '2d4', type: 'electricity', kind: 'damage' }],
      heightening: 'Heightened (+1): damage increases by 1d4.',
    },
  },
  {
    contentId: 'pf2e:spell:spells-srd:force-barrage',
    domain: 'SPELL',
    locale: 'en-US',
    sourceHash: 'git-blob:c92171de982d94a73361f42b3cf5a15426b37258',
    translatableHash: 'git-blob:c92171de982d94a73361f42b3cf5a15426b37258',
    source: { sourcePack: 'spells-srd', sourceId: 'gKKqvLohtrSJj3BM', slug: 'force-barrage', publicationTitle: 'Pathfinder Player Core', license: 'ORC', remaster: true },
    data: {
      schemaVersion: 1,
      name: 'Force Barrage',
      rank: 1,
      rarity: 'common',
      traits: ['concentrate', 'force', 'manipulate'],
      traditions: ['arcane', 'occult'],
      description: 'You fire a shard of solidified magic that automatically hits and deals 1d4+1 force damage. Each additional casting action creates another shard, up to three.',
      castingTime: '1 to 3 actions',
      range: '120 feet',
      target: '1 creature per shard',
      area: null,
      duration: 'instantaneous',
      defense: null,
      damage: [{ formula: '1d4+1', type: 'force', kind: 'damage' }],
      heightening: 'Heightened (+2): fire one additional shard for each action spent.',
    },
  },
  {
    contentId: 'pf2e:spell:spells-srd:heal',
    domain: 'SPELL',
    locale: 'en-US',
    sourceHash: 'git-blob:104b9892805d3248b2afea3ecaced5c3c93d53d8',
    translatableHash: 'git-blob:104b9892805d3248b2afea3ecaced5c3c93d53d8',
    source: { sourcePack: 'spells-srd', sourceId: 'rfZpqmj0AIIdkVIs', slug: 'heal', publicationTitle: 'Pathfinder Player Core', license: 'ORC', remaster: true },
    data: {
      schemaVersion: 1,
      name: 'Heal',
      rank: 1,
      rarity: 'common',
      traits: ['healing', 'manipulate', 'vitality'],
      traditions: ['divine', 'primal'],
      description: 'You channel vital energy to restore 1d8 Hit Points to a willing living creature or deal 1d8 vitality damage to an undead target. The number of actions changes range and targets.',
      castingTime: '1 to 3 actions',
      range: 'varies',
      target: '1 willing living creature, 1 undead, or all living and undead creatures in a 30-foot emanation',
      area: '30-foot emanation with 3 actions',
      duration: 'instantaneous',
      defense: 'basic Fortitude save for undead targets',
      damage: [{ formula: '1d8', type: 'vitality', kind: 'damage-or-healing' }],
      heightening: 'Heightened (+1): healing or damage increases by 1d8; the 2-action healing bonus increases by 8.',
    },
  },
]
