import type { Pathfinder2eOriginalContentRecord } from '../../records'
import type { Pathfinder2eBestiaryData } from '../types'

const DEFAULT_NPC_ICON = '/api/game-systems/pathfinder-2e/icons/default-icons/npc.svg'

export const PATHFINDER_MONSTER_CORE_BESTIARY_ORIGINALS: readonly Pathfinder2eOriginalContentRecord<Pathfinder2eBestiaryData>[] = [
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:goblin-warrior',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'git-blob:d242458d376fb3f258e8a9c20cc7e2f500c298a1',
    translatableHash: 'git-blob:d242458d376fb3f258e8a9c20cc7e2f500c298a1',
    source: { sourcePack: 'pathfinder-monster-core', sourceId: 'fLLKuOXwPq1Iq0U4', slug: 'goblin-warrior', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { path: DEFAULT_NPC_ICON },
    data: {
      schemaVersion: 1,
      name: 'Goblin Warrior',
      level: -1,
      rarity: 'common',
      size: 'small',
      traits: ['goblin', 'humanoid'],
      description: 'Frontline goblin fighters prefer to battle in large groups and overwhelm enemies through numbers and mobility.',
      armorClass: 16,
      hitPoints: 6,
      speedFeet: 25,
      perception: { modifier: 2, senses: ['darkvision'] },
      saves: { fortitude: 5, reflex: 7, will: 3 },
      abilities: { str: 0, dex: 3, con: 1, int: 0, wis: -1, cha: 1 },
      skills: { acrobatics: 5, athletics: 2, nature: 1, stealth: 5 },
      languages: ['goblin', 'common'],
      defenses: { immunities: [], resistances: [], weaknesses: [] },
      attacks: [
        { id: 'CnmgzGmi2Avq67QA', name: 'Dogslicer', bonus: 7, damage: '1d6 slashing', traits: ['agile', 'backstabber', 'finesse'] },
        { id: '4EXgRMqNIRLXxB1c', name: 'Shortbow', bonus: 7, damage: '1d6 piercing', traits: ['deadly-d10', 'reload-0'] },
      ],
      actions: [{ id: 'czwGWW73rkPW7vBg', name: 'Goblin Scuttle', kind: 'reaction', description: 'When a goblin ally ends a move action adjacent to the warrior, the warrior Steps.' }],
    },
  },
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:wolf',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'git-blob:d93e78ff6feddaf9c7114e900bc13c718bc924c9',
    translatableHash: 'git-blob:d93e78ff6feddaf9c7114e900bc13c718bc924c9',
    source: { sourcePack: 'pathfinder-monster-core', sourceId: 'BN5Lb6IsQ9Wyu3rL', slug: 'wolf', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { path: DEFAULT_NPC_ICON },
    data: {
      schemaVersion: 1,
      name: 'Wolf',
      level: 1,
      rarity: 'common',
      size: 'medium',
      traits: ['animal'],
      description: 'Wolves hunt in packs, surround vulnerable prey, and gain an advantage when allies are close to the same target.',
      armorClass: 15,
      hitPoints: 24,
      speedFeet: 35,
      perception: { modifier: 7, senses: ['low-light-vision', 'scent-imprecise-30'] },
      saves: { fortitude: 6, reflex: 9, will: 5 },
      abilities: { str: 2, dex: 4, con: 1, int: -4, wis: 2, cha: -2 },
      skills: { acrobatics: 7, athletics: 6, stealth: 7, survival: 7 },
      languages: [],
      defenses: { immunities: [], resistances: [], weaknesses: [] },
      attacks: [{ id: 'NX0owCPUZbsVJ4az', name: 'Jaws', bonus: 9, damage: '1d6+2 piercing', traits: ['unarmed', 'knockdown'] }],
      actions: [
        { id: 'GhRRqxvK6T21zheo', name: 'Pack Attack', kind: 'passive', description: "The wolf's Strikes deal 1d4 extra damage to creatures within reach of at least two of the wolf's allies." },
        { id: 'dB4Pr3yiNKH32fE8', name: 'Knockdown', kind: 'action', description: 'Standard bestiary Knockdown action.' },
      ],
    },
  },
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:skeleton-guard',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'git-blob:fb28b14a418faa3e0db57c8a3bc534ba4643dd97',
    translatableHash: 'git-blob:fb28b14a418faa3e0db57c8a3bc534ba4643dd97',
    source: { sourcePack: 'pathfinder-monster-core', sourceId: 'trchDxbDR2TiPMxT', slug: 'skeleton-guard', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { path: DEFAULT_NPC_ICON },
    data: {
      schemaVersion: 1,
      name: 'Skeleton Guard',
      level: -1,
      rarity: 'common',
      size: 'medium',
      traits: ['mindless', 'skeleton', 'undead', 'unholy'],
      description: 'Skeleton guards are among the most common animated undead and are usually created to protect a location.',
      armorClass: 16,
      hitPoints: 4,
      speedFeet: 25,
      perception: { modifier: 2, senses: ['darkvision'] },
      saves: { fortitude: 2, reflex: 8, will: 2 },
      abilities: { str: 2, dex: 4, con: 0, int: -5, wis: 0, cha: 0 },
      skills: { acrobatics: 6, athletics: 3 },
      languages: [],
      defenses: {
        immunities: ['death-effects', 'disease', 'paralyzed', 'poison', 'unconscious', 'bleed'],
        resistances: ['cold 5', 'electricity 5', 'fire 5', 'piercing 5', 'slashing 5'],
        weaknesses: [],
      },
      attacks: [
        { id: 'jL9PDQ27Dz6UAMOH', name: 'Scimitar', bonus: 6, damage: '1d6+2 slashing', traits: ['forceful', 'sweep'] },
        { id: 'EzSKWtWM2tSTtZwA', name: 'Claw', bonus: 6, damage: '1d4+2 slashing', traits: ['agile', 'finesse', 'unarmed'] },
        { id: '7ODNVUAaNraSivsT', name: 'Shortbow', bonus: 6, damage: '1d6 piercing', traits: ['deadly-d10', 'reload-0'] },
      ],
      actions: [{ id: 'm25t326n1Ovt0t5U', name: 'Void Healing', kind: 'passive', description: 'The creature is healed by void effects and harmed by vitality effects.' }],
    },
  },
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:animated-statue',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'sha256:b0b3e195176530cd99987a9dc1383b438009a9378374fee85b31ac8972422452',
    translatableHash: 'sha256:33ec37da557fa2e863d8770ddc4f1a369137f74c4a07602437efb29ceba6a4e3',
    source: { sourcePack: 'pathfinder-monster-core', sourceId: 'yQ2mosomuAPiLMkU', slug: 'animated-statue', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { path: DEFAULT_NPC_ICON },
    data: {
      schemaVersion: 1,
      name: 'Animated Statue',
      level: 3,
      rarity: 'common',
      size: 'medium',
      traits: ['construct', 'mindless'],
      description: 'Animated statues guard crypts, shrines, and civic buildings, often hiding among ordinary statues until an intruder draws their attention.',
      armorClass: 19,
      hitPoints: 35,
      speedFeet: 20,
      perception: { modifier: 9, senses: ['darkvision'] },
      saves: { fortitude: 12, reflex: 5, will: 5 },
      abilities: { str: 4, dex: -2, con: 5, int: -5, wis: 0, cha: -5 },
      skills: { athletics: 11 },
      languages: [],
      defenses: { immunities: [], resistances: [], weaknesses: [] },
      attacks: [
        { id: 'animated-statue-fist', name: 'Fist', bonus: 11, damage: '1d8+6 bludgeoning', traits: ['magical', 'unarmed'] },
      ],
      actions: [
        {
          id: 'animated-statue-construct-armor',
          name: 'Construct Armor (Hardness 6)',
          kind: 'passive',
          description: 'Hardness reduces damage by 6. Once the statue has fewer than half its Hit Points, or after it takes damage from a critical hit, its construct armor breaks and its Armor Class is reduced to 15.',
        },
        {
          id: 'animated-statue-grab',
          name: 'Grab',
          kind: 'action',
          description: 'The animated statue Grabs a creature after a successful Strike.',
        },
      ],
    },
  },
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:dryad',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'sha256:1d68b72d115242dd5584ec31ed34170fb3a1c2417ebdd877a63a2a2d2481acce',
    translatableHash: 'sha256:a30a14f39d6218287e7215743ae0112098b7197a2718d987ec17ea8ffe51dc50',
    source: { sourcePack: 'pathfinder-monster-core', sourceId: '4MoqBCDQA6FR1sPw', slug: 'dryad', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { path: DEFAULT_NPC_ICON },
    data: {
      schemaVersion: 1,
      name: 'Dryad',
      level: 3,
      rarity: 'common',
      size: 'medium',
      traits: ['fey', 'nymph', 'plant', 'wood'],
      description: 'Dryads are fey guardians of trees and wooded places. They favor persuasion and enchantment but defend their sacred groves when peaceful warnings fail.',
      armorClass: 17,
      hitPoints: 55,
      speedFeet: 25,
      perception: { modifier: 10, senses: ['low-light-vision'] },
      saves: { fortitude: 6, reflex: 11, will: 10 },
      abilities: { str: 0, dex: 4, con: 1, int: 2, wis: 3, cha: 4 },
      skills: { acrobatics: 9, athletics: 5, crafting: 7, diplomacy: 9, nature: 13, stealth: 9, survival: 12 },
      languages: ['common', 'elven', 'fey', 'muan'],
      defenses: { immunities: [], resistances: [], weaknesses: ['cold-iron 5', 'fire 5'] },
      attacks: [
        { id: 'dryad-branch', name: 'Branch', bonus: 12, damage: '1d12+2 bludgeoning', traits: ['finesse', 'magical'] },
      ],
      actions: [
        {
          id: 'dryad-nature-empathy',
          name: 'Nature Empathy',
          kind: 'passive',
          description: 'The dryad can ask questions of, receive answers from, and use Diplomacy with animals and plants.',
        },
        {
          id: 'dryad-constant-spells',
          name: 'Constant Spells',
          kind: 'passive',
          description: 'The dryad benefits from the constant spells listed in its source stat block.',
        },
        {
          id: 'dryad-tree-dependent',
          name: 'Tree Dependent',
          kind: 'passive',
          description: 'The dryad is bonded to a great tree. Remaining more than 300 feet from it for 24 hours weakens the dryad until it returns.',
        },
        {
          id: 'dryad-tree-meld',
          name: 'Tree Meld',
          kind: 'action',
          description: 'The dryad merges with its bonded tree and can enter an extradimensional living space inside it with up to two adjacent willing creatures.',
        },
      ],
    },
  },
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:griffon',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'sha256:72ea29e4af04a1ea9236547ab0c14cdd5a55b06ffc633117e8786976a671dc8b',
    translatableHash: 'sha256:2f27cf00052ef524de50638935eb210fc70a81cc65be96a53fd78ab6416782f1',
    source: { sourcePack: 'pathfinder-monster-core', sourceId: 'gWgMg7cARqOe82O6', slug: 'griffon', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { path: DEFAULT_NPC_ICON },
    data: {
      schemaVersion: 1,
      name: 'Griffon',
      level: 4,
      rarity: 'common',
      size: 'large',
      traits: ['animal'],
      description: 'Griffons are regal beasts with a great cat’s hindquarters and the head, wings, and forelimbs of a bird of prey. Many cultures revere them as symbols of freedom and strength.',
      armorClass: 21,
      hitPoints: 60,
      speedFeet: 25,
      perception: { modifier: 13, senses: ['darkvision', 'scent-imprecise-60'] },
      saves: { fortitude: 13, reflex: 13, will: 7 },
      abilities: { str: 4, dex: 3, con: 3, int: -4, wis: 1, cha: 2 },
      skills: { acrobatics: 11, athletics: 12, intimidation: 10, stealth: 11, survival: 9 },
      languages: [],
      defenses: { immunities: [], resistances: [], weaknesses: [] },
      attacks: [
        { id: 'griffon-beak', name: 'Beak', bonus: 14, damage: '2d8+4 piercing', traits: ['deadly-d10', 'unarmed'] },
        { id: 'griffon-talon', name: 'Talon', bonus: 14, damage: '2d6+4 piercing', traits: ['agile', 'unarmed'] },
        { id: 'griffon-wing', name: 'Wing', bonus: 14, damage: '2d6+4 bludgeoning', traits: ['reach-10'] },
      ],
      actions: [
        {
          id: 'griffon-flying-strafe',
          name: 'Flying Strafe',
          kind: 'action',
          description: 'The griffon Flies up to its fly Speed and makes two talon Strikes during that movement, each against a different creature.',
        },
        {
          id: 'griffon-pounce',
          name: 'Pounce',
          kind: 'action',
          description: 'The griffon Strides and makes a talon Strike at the end of that movement.',
        },
        {
          id: 'griffon-regal-shriek',
          name: 'Regal Shriek',
          kind: 'action',
          description: 'The griffon unleashes a terrifying shriek. Creatures in a 60-foot emanation attempt a Will save and can become frightened.',
        },
      ],
    },
  },
]
