import type { Pathfinder2eOriginalContentRecord } from '../../records'
import type { Pathfinder2eBestiaryData } from '../types'

export const PATHFINDER_MONSTER_CORE_BESTIARY_ORIGINALS: readonly Pathfinder2eOriginalContentRecord<Pathfinder2eBestiaryData>[] = [
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:goblin-warrior',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'git-blob:d242458d376fb3f258e8a9c20cc7e2f500c298a1',
    translatableHash: 'git-blob:d242458d376fb3f258e8a9c20cc7e2f500c298a1',
    source: { provider: 'FOUNDRY_PF2E', sourcePack: 'pathfinder-monster-core', sourceId: 'fLLKuOXwPq1Iq0U4', slug: 'goblin-warrior', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { upstreamPath: 'systems/pf2e/icons/default-icons/npc.svg' },
    data: {
      schemaVersion: 1,
      name: 'Goblin Warrior',
      level: -1,
      rarity: 'common',
      size: 'small',
      traits: ['goblin', 'humanoid'],
      description: 'Frontline goblin fighters prefer to battle in large groups and overwhelm enemies through numbers and mobility.',
      armorClass: 16,
      hitPoints: 6,
      speedFeet: 25,
      perception: { modifier: 2, senses: ['darkvision'] },
      saves: { fortitude: 5, reflex: 7, will: 3 },
      abilities: { str: 0, dex: 3, con: 1, int: 0, wis: -1, cha: 1 },
      skills: { acrobatics: 5, athletics: 2, nature: 1, stealth: 5 },
      languages: ['goblin', 'common'],
      defenses: { immunities: [], resistances: [], weaknesses: [] },
      attacks: [
        { id: 'CnmgzGmi2Avq67QA', name: 'Dogslicer', bonus: 7, damage: '1d6 slashing', traits: ['agile', 'backstabber', 'finesse'] },
        { id: '4EXgRMqNIRLXxB1c', name: 'Shortbow', bonus: 7, damage: '1d6 piercing', traits: ['deadly-d10', 'reload-0'] },
      ],
      actions: [{ id: 'czwGWW73rkPW7vBg', name: 'Goblin Scuttle', kind: 'reaction', description: 'When a goblin ally ends a move action adjacent to the warrior, the warrior Steps.' }],
    },
  },
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:wolf',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'git-blob:d93e78ff6feddaf9c7114e900bc13c718bc924c9',
    translatableHash: 'git-blob:d93e78ff6feddaf9c7114e900bc13c718bc924c9',
    source: { provider: 'FOUNDRY_PF2E', sourcePack: 'pathfinder-monster-core', sourceId: 'BN5Lb6IsQ9Wyu3rL', slug: 'wolf', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { upstreamPath: 'systems/pf2e/icons/default-icons/npc.svg' },
    data: {
      schemaVersion: 1,
      name: 'Wolf',
      level: 1,
      rarity: 'common',
      size: 'medium',
      traits: ['animal'],
      description: 'Wolves hunt in packs, surround vulnerable prey, and gain an advantage when allies are close to the same target.',
      armorClass: 15,
      hitPoints: 24,
      speedFeet: 35,
      perception: { modifier: 7, senses: ['low-light-vision', 'scent-imprecise-30'] },
      saves: { fortitude: 6, reflex: 9, will: 5 },
      abilities: { str: 2, dex: 4, con: 1, int: -4, wis: 2, cha: -2 },
      skills: { acrobatics: 7, athletics: 6, stealth: 7, survival: 7 },
      languages: [],
      defenses: { immunities: [], resistances: [], weaknesses: [] },
      attacks: [{ id: 'NX0owCPUZbsVJ4az', name: 'Jaws', bonus: 9, damage: '1d6+2 piercing', traits: ['unarmed', 'knockdown'] }],
      actions: [
        { id: 'GhRRqxvK6T21zheo', name: 'Pack Attack', kind: 'passive', description: "The wolf's Strikes deal 1d4 extra damage to creatures within reach of at least two of the wolf's allies." },
        { id: 'dB4Pr3yiNKH32fE8', name: 'Knockdown', kind: 'action', description: 'Standard bestiary Knockdown action.' },
      ],
    },
  },
  {
    contentId: 'pf2e:bestiary:pathfinder-monster-core:skeleton-guard',
    domain: 'BESTIARY',
    locale: 'en-US',
    sourceHash: 'git-blob:fb28b14a418faa3e0db57c8a3bc534ba4643dd97',
    translatableHash: 'git-blob:fb28b14a418faa3e0db57c8a3bc534ba4643dd97',
    source: { provider: 'FOUNDRY_PF2E', sourcePack: 'pathfinder-monster-core', sourceId: 'trchDxbDR2TiPMxT', slug: 'skeleton-guard', publicationTitle: 'Pathfinder Monster Core', license: 'ORC', remaster: true },
    image: { upstreamPath: 'systems/pf2e/icons/default-icons/npc.svg' },
    data: {
      schemaVersion: 1,
      name: 'Skeleton Guard',
      level: -1,
      rarity: 'common',
      size: 'medium',
      traits: ['mindless', 'skeleton', 'undead', 'unholy'],
      description: 'Skeleton guards are among the most common animated undead and are usually created to protect a location.',
      armorClass: 16,
      hitPoints: 4,
      speedFeet: 25,
      perception: { modifier: 2, senses: ['darkvision'] },
      saves: { fortitude: 2, reflex: 8, will: 2 },
      abilities: { str: 2, dex: 4, con: 0, int: -5, wis: 0, cha: 0 },
      skills: { acrobatics: 6, athletics: 3 },
      languages: [],
      defenses: {
        immunities: ['death-effects', 'disease', 'paralyzed', 'poison', 'unconscious', 'bleed'],
        resistances: ['cold 5', 'electricity 5', 'fire 5', 'piercing 5', 'slashing 5'],
        weaknesses: [],
      },
      attacks: [
        { id: 'jL9PDQ27Dz6UAMOH', name: 'Scimitar', bonus: 6, damage: '1d6+2 slashing', traits: ['forceful', 'sweep'] },
        { id: 'EzSKWtWM2tSTtZwA', name: 'Claw', bonus: 6, damage: '1d4+2 slashing', traits: ['agile', 'finesse', 'unarmed'] },
        { id: '7ODNVUAaNraSivsT', name: 'Shortbow', bonus: 6, damage: '1d6 piercing', traits: ['deadly-d10', 'reload-0'] },
      ],
      actions: [{ id: 'm25t326n1Ovt0t5U', name: 'Void Healing', kind: 'passive', description: 'The creature is healed by void effects and harmed by vitality effects.' }],
    },
  },
]
