export { AreaOverlay } from './components/AreaOverlay'
export { AreaTemplatesPanel } from './components/AreaTemplatesPanel'
export { AreaEffectContextMenu } from './components/AreaEffectContextMenu'
export { useAreaTemplates } from './hooks/useAreaTemplates'
export { useSharedAreaPreviews } from './hooks/useSharedAreaPreviews'
export { calculateAreaRender, directionDegrees } from './domain/geometry'
export { snapAreaOrigin } from './domain/runtimeGeometry'
export { areaScaleForMeters, primaryAreaDimension } from './domain/instanceMeasurement'
export { findIntersectingTargetTokenId, toggleTargetSelection } from './domain/targetSelection'
export type { AreaPlacement, AreaRenderModel, CampaignAreaTemplate, SceneAreaEffect } from './domain/types'
