// Static names extracted once from branch development:packages/game-system-pathfinder-2e/src/server/character-options/data/backgrounds.generated.ts.
// This file is intentionally independent from the other PF2e select catalogs.
export const PATHFINDER_2E_BACKGROUNDS = [
  "Abadar's Avenger",
  "Able Carter",
  "Academic Scion",
  "Academy Dropout",
  "Acolyte",
  "Acrobat",
  "Acupuncturist",
  "Aerialist",
  "Aiudara Seeker",
  "Alkenstar Outlaw",
  "Alkenstar Sojourner",
  "Alkenstar Tinker",
  "Alloysmith",
  "Almas Clerk",
  "Always Chosen Last",
  "Amateur Director",
  "Amnesiac",
  "Animal Whisperer",
  "Animal Wrangler",
  "Anti-Magical",
  "Anti-Tech Activist",
  "Archaeologist",
  "Art Tutor",
  "Artisan",
  "Artist",
  "Aspiring Free-Captain",
  "Aspiring River Monarch",
  "Astrologer",
  "Astrological Augur",
  "Attention Addict",
  "Atteran Rancher",
  "Awful Scab",
  "Bachuan Revolutionary",
  "Back-Alley Doctor",
  "Badlands Scout",
  "Bandit",
  "Banished Brighite",
  "Banished Celestial",
  "Barber",
  "Barkeep",
  "Barker",
  "Barrister",
  "Beast Blessed",
  "Bekyar Restorer",
  "Belkzen Anthropologist",
  "Belkzen Slayer",
  "Bellflower Agent",
  "Bibliophile",
  "Black Market Smuggler",
  "Blessed",
  "Blight Survivor",
  "Blow-In",
  "Bonuwat Wavetouched",
  "Bookish Providence",
  "Bookkeeper",
  "Borderlands Pioneer",
  "Bounty Hunter",
  "Brevic Noble",
  "Brevic Outcast",
  "Bright Lion",
  "Broken Tusk Recruiter",
  "Bully or Baiter?",
  "Butcher",
  "Cannoneer",
  "Cathedral Child",
  "Charlatan",
  "Chelish Rebel",
  "Child Of Notoriety",
  "Child of the Colony",
  "Child of the Puddles",
  "Child of the Twin Village",
  "Child of Westcrown",
  "Chosen One",
  "Circuit Judge",
  "Circus Born",
  "Clan Associate",
  "Clockfighter",
  "Clockwork Researcher",
  "Close Ties",
  "Clown",
  "Codebreaker",
  "Company Agent",
  "Concordance Researcher",
  "Concordance Scout",
  "Conservator",
  "Construction Occultist",
  "Convocation Scout",
  "Cook",
  "Corpse Stitcher",
  "Courier",
  "Criminal",
  "Crown of Chaos",
  "Crystal Healer",
  "Cultist",
  "Curandero",
  "Curious Apprentice",
  "Cursed",
  "Cursed Family",
  "Dauntless",
  "Deckhand",
  "Dedicated Delver",
  "Deep-Sea Diver",
  "Demon Hunted",
  "Demon Slayer",
  "Dendrologist",
  "Deputy",
  "Desert Tracker",
  "Detective",
  "Diobel Pearl Diver",
  "Discarded Duplicate",
  "Disciple of the Gear",
  "Doomcaller",
  "Dragon Scholar",
  "Dreamer of the Verdant Moon",
  "Dreams of Vengeance",
  "Driver",
  "Droskari Disciple",
  "Eager Scofflaw",
  "Eagle Hunter",
  "Early Explorer",
  "Eclectic Scholar",
  "Eclipseborn",
  "Eidolon Contact",
  "Eldritch Anatomist",
  "Elementally Infused",
  "Emancipated",
  "Emissary",
  "Empty Hand Loyalist",
  "Empty Whispers",
  "Energy Scarred",
  "Entertainer",
  "Ex-Con Token Guard",
  "Ex-Mendevian Crusader",
  "Faction Opportunist",
  "False Medium",
  "Farmhand",
  "Farmsteader",
  "Fated Rival",
  "Favored",
  "Feral Child",
  "Fey Friend",
  "Feybound",
  "Field Medic",
  "Fiendbreaking Pilgrim",
  "Fightbreaker",
  "Finadar Leshy",
  "Final Blade Survivor",
  "Fire Warden",
  "Firebrand Follower",
  "Fireworks Performer",
  "Fogfen Tale-Teller",
  "Folklore Enthusiast",
  "Food Trader",
  "Foreign Diplomat",
  "Former Aspis Agent",
  "Fortune Teller",
  "Framed in Ferrous Quarter",
  "Free Spirit",
  "Freed Slave of Absalom",
  "Friend of Greensteeples",
  "Friendly Darkmoon Kobold",
  "Gambler",
  "Geb Crusader",
  "Genie-Blessed",
  "Ghostwriter",
  "Gladiator",
  "Gloriana's Fixer",
  "Goblinblood Orphan",
  "Godless Graycloak",
  "Gold Falls Regular",
  "Goldhand Arms Dealer",
  "Gossip",
  "Grand Council Bureaucrat",
  "Grave Robber",
  "Green Faith Pilgrim",
  "Grizzled Muckrucker",
  "Guard",
  "Guest of Sedeq Lodge",
  "Gunsmith",
  "Hammered by Fate",
  "Harbor Guard Moonlighter",
  "Harrow-Chosen",
  "Harrow-Led",
  "Haunted",
  "Haunted Citizen",
  "Haunting Vision",
  "Hellknight Historian",
  "Herbalist",
  "Hermean Expatriate",
  "Hermean Heritor",
  "Hermit",
  "Highborn Snoop",
  "Hired Killer",
  "Historical Reenactor",
  "Hookclaw Digger",
  "Hounded Thief",
  "Hunted by the Night",
  "Hunter",
  "Inexplicably Expelled",
  "Inlander",
  "Insurgent",
  "Iolite Trainee Hobgoblin",
  "Issian Partisan",
  "Issian Patriot",
  "Jeweler",
  "Junk Collector",
  "Junker",
  "Kaiju Stalker",
  "Kalistrade Follower",
  "Keys to Destiny",
  "Knack for Contraptions",
  "Kyonin Emissary",
  "Laborer",
  "Lastwall Survivor",
  "Learned Guard Prodigy",
  "Legacy of the Hammer",
  "Legendary Parents",
  "Lesser Scion",
  "Library Dweller",
  "Local Brigand",
  "Local Scion",
  "Lost and Alone",
  "Lost Coast Local",
  "Lost Loved One",
  "Lumber Consortium Laborer",
  "Magaambya Academic",
  "Magical Experiment",
  "Magical Merchant",
  "Magical Misfit",
  "Mammoth Herder",
  "Mammoth Speaker",
  "Mana Wastes Refugee",
  "Mantis Scion",
  "Market Runner",
  "Martial Disciple",
  "Mechanic",
  "Mechanical Symbiosis",
  "Medicinal Clocksmith",
  "Megafauna Hunter",
  "Menagerie Dung Sweeper",
  "Merabite Prodigy",
  "Merchant",
  "Militia Member",
  "Miner",
  "Missionary",
  "Molthuni Mercenary",
  "Money Counter",
  "Moot Guard",
  "Mortuarium Survivor",
  "Musical Prodigy",
  "Mystic Seer",
  "Mystic Tutor",
  "Necromancer's Apprentice",
  "Newcomer",
  "Newcomer In Need",
  "Nexian Mystic",
  "Night Watch",
  "Nirmathi Guerrilla",
  "Noble",
  "Nocturnal Navigator",
  "Nomad",
  "Northland Forager",
  "Northridge Scholar",
  "Occult Librarian",
  "Ocean Diver",
  "Oenopion-Ooze Tender",
  "Once Bitten",
  "Onyx Trader",
  "Osirionologist",
  "Osprey Barnraiser",
  "Osprey Fisher",
  "Osprey Scion",
  "Osprey Scout",
  "Osprey Scribe",
  "Osprey Spellcaster",
  "Osprey Warrior",
  "Otherworldly Mission",
  "Out-Of-Towner",
  "Outrider",
  "Outskirt Dweller",
  "Ozem Experience",
  "Party Scholar",
  "Pathfinder Hopeful",
  "Pathfinder Recruiter",
  "Perfection Seeker",
  "Pilgrim",
  "Pillar",
  "Planar Migrant",
  "Plant Whisperer",
  "Political Scion",
  "Portal Scholar",
  "Post Guard of All Trades",
  "Press-Ganged (G&G)",
  "Press-Ganged (LOWG)",
  "Printer",
  "Prisoner",
  "Professional Letter Writer",
  "Propaganda Promoter",
  "Purveyor of the Bizarre",
  "Pyre Tender",
  "Quick",
  "Quick Refugee",
  "Raised by Belief",
  "Ratted-Out Gun Runner",
  "Razmiran Faithful",
  "Reborn Soul",
  "Reclaimed",
  "Reclaimer Investigator",
  "Refugee (Fall of Plaguestone)",
  "Refugee (PC2)",
  "Relentless Dedication",
  "Remittance Agent",
  "Reputation Seeker",
  "Respected Mentor",
  "Returned",
  "Returning Descendant",
  "Revenant",
  "Rigger",
  "Rivethun Adherent",
  "Root Worker",
  "Rostland Partisan",
  "Rostlander",
  "Royalty",
  "Ruby Phoenix Enthusiast",
  "Ruby Phoenix Fanatic",
  "Ruin Delver",
  "Runaway Noble",
  "Runelord Scholar",
  "Runner",
  "Saboteur",
  "Sailor",
  "Sally Guard Neophyte",
  "Saloon Entertainer",
  "Sandswept Survivor",
  "Sarkorian Reclaimer",
  "Sarkorian Survivor",
  "Saved by Clockwork",
  "Savior of Air",
  "Scarnetti-Connected",
  "Scavenger",
  "Scholar",
  "Scholar of the Ancients",
  "Scholar of the Sky Key",
  "School Medic",
  "Scion of Slayers",
  "Scout",
  "Second Chance Champion",
  "Secular Medic",
  "Seer of the Dead",
  "Self-Made",
  "Senghor Sailor",
  "Sense of Belonging",
  "Sentinel Reflectance",
  "Servant",
  "Sewer Dragon",
  "Shadow Haunted",
  "Shadow Lodge Defector",
  "Shadow War Survivor",
  "Sheriff",
  "Shielded Fortune",
  "Shoanti Name-Bearer",
  "Shory Seeker",
  "Sideshow Scion",
  "Sign Bound",
  "Silk Farmer",
  "Sky Rider",
  "Sleepless Suns Star",
  "Snubbed Out Stoolie",
  "Sodden Scavenger",
  "Song of the Deep",
  "Songsinger in Training",
  "Southbank Traditionalist",
  "Spell Seeker",
  "Sponsored by a Stranger",
  "Sponsored by a Village",
  "Sponsored by Family",
  "Sponsored by Teacher Ot",
  "Spotter",
  "Squire",
  "Star Athlete",
  "Stargazer",
  "Starless One",
  "Starwatcher",
  "Storm Survivor",
  "Story Collector",
  "Street Preacher",
  "Street Urchin",
  "Streetfood Vendor",
  "Student of Archery",
  "Student of Magic",
  "Student of the Ancients",
  "Sun Dancer",
  "Supportive Sponsor",
  "Surge Investigator",
  "Sword Scion",
  "Taldan Schemer",
  "Tall Tale",
  "Tapestry Refugee",
  "Tax Collector",
  "Teacher",
  "Teamster",
  "Tech-Reliant",
  "Thassilonian Delver",
  "Thassilonian Traveler",
  "Thrill-Seeker",
  "Thrune Loyalist",
  "Thuvian Unifier",
  "Tide Watcher",
  "Tiffin Box Deliverer",
  "Time Traveler",
  "Tinker",
  "Tomb Born",
  "Total Power",
  "Touched by Dahak",
  "Town Troublemaker",
  "Toymaker",
  "Trade Consortium Underling",
  "Trade Representative",
  "Trailblazer",
  "Translator",
  "Traveling Gourmand",
  "Tree Friend",
  "Truth Seeker",
  "Tyrant Witness",
  "Ulfen Raider",
  "Undercover Contender",
  "Undercover Lotus Guard",
  "Undersea Enthusiast",
  "Undertaker",
  "Union Representative",
  "Unremarkable",
  "Unsponsored",
  "Ustalavic Academic",
  "Varisian Wanderer",
  "Verduran City Folk",
  "Vidrian Reformer",
  "Wandering Libertine",
  "Wandering Preacher",
  "Wanderlust",
  "Wanted Witness",
  "Ward",
  "Warded by Kami",
  "Warrior",
  "Waste Walker",
  "Weaver",
  "Whispering Way Scion",
  "Wildwood Local",
  "Willing Host",
  "Willowshore Urchin",
  "Winter's Child",
  "Wish for Riches",
  "Wished Alive",
  "Witch Wary",
  "Witchlight Follower",
  "Wonder Taster",
  "Wood Warden",
  "Working Student",
  "Writ in the Stars",
  "Zodiac Bound",
] as const
