// Static names extracted once from branch development:packages/game-system-pathfinder-2e/src/server/actor-options/data/classes.generated.ts.
// This file is intentionally independent from the other PF2e select catalogs.
export const PATHFINDER_2E_CLASSES = [
  "Alchemist",
  "Animist",
  "Barbarian",
  "Bard",
  "Champion",
  "Cleric",
  "Druid",
  "Exemplar",
  "Fighter",
  "Gunslinger",
  "Inventor",
  "Investigator",
  "Kineticist",
  "Magus",
  "Monk",
  "Oracle",
  "Psychic",
  "Ranger",
  "Rogue",
  "Sorcerer",
  "Summoner",
  "Swashbuckler",
  "Thaumaturge",
  "Witch",
  "Wizard",
] as const
