// Static names extracted once from foundryvtt/pf2e@5069fb7a421a5ba1789652764447cced91ffb0e2:packs/pf2e/deities.
// This file is intentionally independent from the other PF2e select catalogs.
export const PATHFINDER_2E_DEITIES = [
  "Aakriti",
  "Abadar",
  "Abraxas",
  "Abrogail",
  "Acavna",
  "Achaekek",
  "Adanye",
  "Aegirran",
  "Aerekostes",
  "Aesocar",
  "Ah Pook",
  "Ahriman",
  "Alazhra",
  "Aleth",
  "Alglenweis",
  "Alocer",
  "Alseta",
  "Amaznen",
  "Aminara",
  "Ananshea",
  "Andoletta",
  "Angazhan",
  "Angradd",
  "Anogetz",
  "Anras",
  "Anubis",
  "Aonaurious",
  "Apep",
  "Apollyon",
  "Apsu",
  "Arazni",
  "Ardad Lili",
  "Areshkagal",
  "Aroden",
  "Arqueros",
  "Arshea",
  "Arundhat",
  "Ashava",
  "Ashukharma",
  "Asmodeus",
  "Atheists and Free Agents",
  "Atreia",
  "Atrogine",
  "Atropos",
  "Ayrzul",
  "Azathoth",
  "Baalzebul",
  "Baekho",
  "Balumbdar",
  "Baphomet",
  "Barbatos",
  "Barzahk",
  "Bastet",
  "Belech",
  "Belial",
  "Bergelmir",
  "Bes",
  "Besmara",
  "Bharnarol",
  "Bifrons",
  "Black Butterfly",
  "Blooms of the Spreading Weald",
  "Bokrug",
  "Bolka",
  "Breath of the Endless Sky",
  "Brigh",
  "Brixori",
  "Calistria",
  "Camazotz",
  "Casandalee",
  "Cayden Cailean",
  "Cernunnos",
  "Ceyannan",
  "Chaldira",
  "Chamiaholom",
  "Chamidu",
  "Charg",
  "Charon",
  "Chavazvug",
  "Children of the Night",
  "Chinostes",
  "Chohar",
  "Cihua Coatl",
  "Cixyron",
  "Cong",
  "Conqueror Worm",
  "Cormigus",
  "Cormion",
  "Corosbel",
  "Cosmic Caravan",
  "Count Ranalc",
  "Cthulhu",
  "Cyth-V'sug",
  "Dachzerul",
  "Dagon",
  "Dahak",
  "Daikitsu",
  "Dajermube",
  "Dalenydra",
  "Dammar",
  "Dammerich",
  "Demon Bringers",
  "Deshto",
  "Desna",
  "Dhalavei",
  "Diomazul",
  "Dispater",
  "Dolok Darkfur",
  "Doloras",
  "Dramindyr",
  "Dranngvit",
  "Drokalion",
  "Droskar",
  "Eiseth",
  "Elion",
  "Embaral",
  "Emmeton Galardaria",
  "Enkaar",
  "Erastil",
  "Erecura",
  "Eritrice",
  "Esoteric Order of the Palatine Eye",
  "Essence Dancers",
  "Etaris",
  "Eyes That Watch",
  "Faith in the Fallen",
  "Falayna",
  "Fandarra",
  "Ferrumnestra",
  "Findeladlara",
  "Folgrit",
  "Fortune's Fate",
  "Fumeiyoshi",
  "Furcas",
  "Gaasham",
  "Garhaazh",
  "Gendowyn",
  "General Susumu",
  "Genzaeri",
  "Geryon",
  "Ghlaunder",
  "God Calling",
  "Gogunta",
  "Good Neighbors",
  "Gorum",
  "Gozreh",
  "Grandmother Spider",
  "Granduncle Taproot",
  "Grask Uldeth",
  "Grasping Iovett",
  "Gravelady's Guard",
  "Green Faith",
  "Green Man",
  "Groetus",
  "Gruhastha",
  "Grundinnar",
  "Guardians of the Sacred Self",
  "Gyronna",
  "Haagenti",
  "Haborym",
  "Hadregash",
  "Haggakal",
  "Halcamora",
  "Hanspur",
  "Hastur",
  "Hataam",
  "Hathor",
  "Hearth and Harvest",
  "Hei Feng",
  "Horus",
  "Hshurha",
  "Husk",
  "Iapholi",
  "Iggeret",
  "Il'Surrish",
  "Imbrex",
  "Immaculate Growth",
  "Immonhiel",
  "Imot",
  "Inna",
  "Iomedae",
  "Irez",
  "Irori",
  "Isis",
  "Isph-Aun-Vuln",
  "Izuyaku",
  "Jaidi",
  "Jaidz",
  "Jezelda",
  "Jin Li",
  "Jukha",
  "Kabriri",
  "Kagia",
  "Kaldemash",
  "Kalekot",
  "Kazutal",
  "Keepers of the Hearth",
  "Kelinahat",
  "Kelizandri",
  "Keltheald",
  "Kerkamoth",
  "Ketephys",
  "Khepri",
  "Kitumu",
  "Kofusachi",
  "Kols",
  "Korada",
  "Kostchtchie",
  "Kurgess",
  "Kzininn",
  "Lady Jingxi",
  "Lady Nanbyo",
  "Lady Razor",
  "Lahkgya",
  "Laivatiniel",
  "Lalaci",
  "Lamashtu",
  "Lao Shu Po",
  "Laudinmio",
  "Laws of Mortality",
  "Light of the Everlasting Flame",
  "Liisglan",
  "Likha",
  "Lissala",
  "Lissala (The Order of Virtue)",
  "Lorris",
  "Lorthact",
  "Lubaiko",
  "Luhar",
  "Lurlup",
  "Lymnieris",
  "Lysianassa",
  "Ma'at",
  "Magdh",
  "Magrim",
  "Mahathallah",
  "Mahja Firehair",
  "Malthus",
  "Mammon",
  "Marishi",
  "Matravash",
  "Mazludeh",
  "Mephistopheles",
  "Mestama",
  "Mhar",
  "Milani",
  "Minderhal",
  "Moloch",
  "Monad",
  "Mother Vulture",
  "Mrtyu",
  "Mugura and Nrithu",
  "Myr",
  "Naderi",
  "Nalinivati",
  "Nameless",
  "Narakaas",
  "Narriseminek",
  "Neith",
  "Nephthys",
  "Nergal",
  "Neshen",
  "Nethys",
  "Ng",
  "Nhimbaloth",
  "Nin",
  "Nivi Rhombodazzle",
  "Nocticula",
  "Norgorber",
  "Norns",
  "Nulgreth",
  "Nurgal",
  "Nyarlathotep (Haunter in the Dark)",
  "Nyarlathotep (The Crawling Chaos)",
  "Nyarlathotep (The Faceless Sphinx)",
  "Nyarlathotep (The Veiled Voice)",
  "Nyuo-Ogh",
  "Oathos",
  "Oaur-Ooung",
  "Obari",
  "Olheon",
  "Ongalte",
  "Onos",
  "Orcus",
  "Orgesh",
  "Osiris",
  "Otilaz",
  "Otolmens",
  "Ozranvial",
  "Pahti Coatl",
  "Pavnuri",
  "Pazuzu",
  "Pharasma",
  "Pharimia",
  "Phi Deva",
  "Phlegyas",
  "Picoperi",
  "Pillars of Knowledge",
  "Prophecies of Kalistrade",
  "Ptah",
  "Pulura",
  "Qi Zhong",
  "Ra",
  "Radiant Prism",
  "Ragadahn",
  "Ragathiel",
  "Ragdya",
  "Ranginori",
  "Raumya",
  "Ravithra",
  "Razmir",
  "Reshmit of the Heavy Voice",
  "Reymenda",
  "Rhan-Tegoth",
  "Ristrentho",
  "Rivethun",
  "Rokoga Gin",
  "Rovagug",
  "Rowdrosh",
  "Rull",
  "Sairazul",
  "Saloc",
  "Sangpotshi",
  "Sarenrae",
  "Sarshallatu",
  "Scal",
  "Seafarers' Hope",
  "Sekhmet",
  "Selket",
  "Seramaydiel",
  "Set",
  "Shadow Cabinet",
  "Shapes of the Fading Luster",
  "Shawnari",
  "Shax",
  "Shei",
  "Shelyn",
  "Shivaska",
  "Shizuru",
  "Shoanti Animism",
  "Shumunue",
  "Shyka",
  "Sicva",
  "Sifkesh",
  "Sithhud",
  "Sivanah",
  "Skode",
  "Skrymir",
  "Sky Keepers",
  "Smiad",
  "Sobek",
  "Soralyon",
  "Sorrow's Sword",
  "Sovyrian Conclave",
  "Srikalis, Sritaming, and Sribaril",
  "Ssila'meshnik",
  "Stag Mother of the Forest of Stones",
  "Stone's Blood",
  "Sturovenen",
  "Sun Wukong",
  "Surveyors of the Deep",
  "Suyuddha",
  "Szuriel",
  "Talons of the Godclaw",
  "Tanagaar",
  "Teki Stronggut",
  "Telastmar",
  "Telvrys",
  "Teshallas",
  "Thalaphyrr",
  "Thamir",
  "The Anointing of Kings",
  "The Curtain Call",
  "The Deliberate Journey",
  "The Devourer",
  "The Divine Dare",
  "The Endless Road",
  "The Enlightened Scholar's Path",
  "The Freeing Flame",
  "The Godclaw",
  "The Green Mother",
  "The Laborer's Bastion",
  "The Lady of the North Star",
  "The Lantern King",
  "The Last Breath",
  "The Lost Prince",
  "The Offering Plate",
  "The Pale Horse",
  "The Pandemonia",
  "The Path of the Heavens",
  "The Perplexing Jest",
  "The Readied Strike",
  "The Resplendent Court",
  "The Spirit Wall",
  "The Tides of Chaos",
  "Thisamet",
  "Thoth",
  "Thremyr",
  "Thuskchoon",
  "Titivilus",
  "Tjasse",
  "Tlehar",
  "Tolte Coatl",
  "Torag",
  "Touch of the Sun",
  "Treasures of the Eternal Delve",
  "Treerazer",
  "Trelmarixian",
  "Tresmalvos",
  "Trudd",
  "Tsukiyo",
  "Turvu",
  "Uirch",
  "Ulon",
  "Umarik",
  "Upion and Warrik",
  "Urazra",
  "Urban Prosperity",
  "Urgathoa",
  "Uskyeria",
  "Ussharassim",
  "Uvuko",
  "Valani",
  "Vale",
  "Valmallos",
  "Vapula",
  "Varg",
  "Vavaalrav",
  "Velgaas",
  "Venkelvore",
  "Verilorn",
  "Vermilion Mother",
  "Vildeis",
  "Vineshvakhi",
  "Vonymos",
  "Vorasha",
  "Vudravati",
  "Vulot",
  "Wadjet",
  "Walkena",
  "Wards of the Pharaoh",
  "Waves of the Boundless Sea",
  "Weight of the World",
  "Wheels of Innovation",
  "Whispering Way",
  "Winlas",
  "Wulgren",
  "Xhamen-Dor",
  "Xiquiripat",
  "Xoveron",
  "Xsistaid",
  "Yaezhing",
  "Yamasoth",
  "Yamatsumi",
  "Ydajisk",
  "Ydersius",
  "Yelayne",
  "Yhidothrus",
  "Yig",
  "Ylimancha",
  "Yluma",
  "Ymeri",
  "Yog-Sothoth",
  "Yrmidar",
  "Ytildos",
  "Yuelral",
  "Zarongel",
  "Zeaki",
  "Zelishkar",
  "Zevgavizeb",
  "Zibik",
  "Zipacna",
  "Zjar-Tovan",
  "Zogmugot",
  "Zohls",
  "Zon-Kuthon",
  "Zugero",
  "Zura",
  "Zursvaater",
  "Zyphus",
] as const
