// Static names extracted once from branch development:packages/game-system-pathfinder-2e/src/server/actor-options/data/heritages.generated.ts.
// This file is intentionally independent from the other PF2e select catalogs.
export const PATHFINDER_2E_HERITAGES = [
  "Abyssal Merfolk",
  "Adaptive Anadi",
  "Aiuvarin",
  "Ancient Ash",
  "Ancient Elf",
  "Ancient Scale Azarketi",
  "Ancient-Blooded Dwarf",
  "Ant Kholo",
  "Anvil Dwarf",
  "Arctic Elf",
  "Ardande",
  "Artisan Android",
  "Ascetic Tanuki",
  "Athamasi",
  "Badlands Orc",
  "Bakuwa Lizardfolk",
  "Bandaagee Vanara",
  "Battle-Ready Orc",
  "Battle-Trained Human (BB)",
  "Beastkin",
  "Benthic Azarketi",
  "Bloodhound Shoony",
  "Born of Animal",
  "Born of Celestial",
  "Born of Elements",
  "Born of Item",
  "Born of Vegetation",
  "Breaker Surki",
  "Bright Fetchling",
  "Budding Speaker Centaur",
  "Cactus Leshy",
  "Carcharodon Merfolk",
  "Cataphract Fleshwarp",
  "Cave Kholo",
  "Caveclimber Kobold",
  "Cavern Elf",
  "Cavernstalker Kobold",
  "Celestial Envoy Kitsune",
  "Chameleon Gnome",
  "Changeling",
  "Charhide Goblin",
  "Chrysanthemum Leshy",
  "Clawed Catfolk",
  "Cliffscale Lizardfolk",
  "Climbing Animal",
  "Cloudleaper Lizardfolk",
  "Compact Skeleton",
  "Coral Athamaru",
  "Courageous Tanuki",
  "Created Fleshwarp",
  "Dark Fields Kitsune",
  "Death Warden Dwarf",
  "Deep Fetchling",
  "Deep Orc",
  "Deep Rat",
  "Deny Lady Nanbyo's Charity",
  "Deny the Firstborn Pursuit",
  "Deny the Traitor's Rebirth",
  "Desert Elf",
  "Desert Rat",
  "Dhampir",
  "Dijiang",
  "Discarded Fleshwarp",
  "Dog Kholo",
  "Dogtooth Tengu",
  "Dokkaebi Goblin",
  "Dragonblood",
  "Dragonscaled Kobold",
  "Draxie",
  "Dromaar",
  "Duskwalker",
  "Earthly Wilds Kitsune",
  "Elemental Heart Dwarf",
  "Elementheart Kobold",
  "Elfbane Hobgoblin",
  "Elusive Vishkanya",
  "Elytron Surki",
  "Empty Sky Kitsune",
  "Enchanting Lily",
  "Even-Tempered Tanuki",
  "Farsight Goloma",
  "Fey-Touched Gnome",
  "Fishseeker Shoony",
  "Fleetwind Centaur",
  "Flexible Catfolk",
  "Flying Animal",
  "Fodder Skeleton",
  "Forge Dwarf",
  "Forge-Blessed Dwarf",
  "Frightful Goloma",
  "Frilled Lizardfolk",
  "Frozen Wind Kitsune",
  "Fruit Leshy",
  "Full Moon Sarangay",
  "Fungus Leshy",
  "Gandharva",
  "Ghost Bull Minotaur",
  "Ghost Poppet",
  "Glacier Cavern Minotaur",
  "Gourd Leshy",
  "Grave Orc",
  "Great Kholo",
  "Grig",
  "Gutsy Halfling",
  "Half Moon Sarangay",
  "Hardshell Surki",
  "Healer Samsaran",
  "Heavenscribe Kobold",
  "Hillock Halfling",
  "Hold-Scarred Orc",
  "Hooded Nagaji",
  "Hopeful Athamaru",
  "Hungerseed",
  "Hunter Automaton",
  "Hunting Catfolk",
  "Impersonator Android",
  "Insightful Goloma",
  "Inured Azarketi",
  "Irongut Goblin",
  "Ironhoof Centaur",
  "Jinxed Halfling",
  "Jinxed Tengu",
  "Jungle Catfolk",
  "Kaleidoscopic Athamaru",
  "Kanchil",
  "Keen-Venom Vishkanya",
  "Kijimuna Gnome",
  "Laborer Android",
  "Lahkgyan Vanara",
  "Lantern Surki",
  "Leaf Leshy",
  "Lethoci",
  "Leungli",
  "Liminal Catfolk",
  "Liminal Fetchling",
  "Littlehorn Minotaur",
  "Longsnout Rat",
  "Lorekeeper Shisk",
  "Lotus Leshy",
  "Luminous Sprite",
  "Mage Automaton",
  "Makari Lizardfolk",
  "Melixie",
  "Mightyfall Kobold",
  "Mistbreath Azarketi",
  "Monstrous Skeleton",
  "Mottle-Coat Centaur",
  "Mountaineer Samsaran",
  "Mountainkeeper Tengu",
  "Murkeyed Azarketi",
  "Mutated Fleshwarp",
  "Naari",
  "Nascent",
  "Nephilim",
  "New Moon Sarangay",
  "Nightglider Strix",
  "Nine Lives Catfolk",
  "Nomadic Halfling",
  "Nyktera",
  "Oathkeeper Dwarf",
  "Observant Halfling",
  "Old-Blood Vishkanya",
  "Oracular Samsaran",
  "Oread",
  "Paddler Shoony",
  "Palace Echoes Kitsune",
  "Peachchild Leshy",
  "Pelagic Merfolk",
  "Pine Leshy",
  "Pixie",
  "Poisonhide Tripkee",
  "Polychromatic Anadi",
  "Polyglot Android",
  "Ponygait Centaur",
  "Predator Strix",
  "Prismatic Vishkanya",
  "Quillcoat Shisk",
  "Quilled Athamaru",
  "Ragdyan Vanara",
  "Rainfall Orc",
  "Razortooth Goblin",
  "Reef Merfolk",
  "Reflection",
  "Resolute Fetchling",
  "Respite of a Thousand Roofs",
  "Respite of Cloudless Paths",
  "Respite of Loam and Leaf",
  "Rite of Invocation",
  "Rite of Knowing",
  "Rite of Light",
  "Rite of Passage",
  "Rite of Reinforcement",
  "River Azarketi",
  "Riverside Tripkee",
  "Roaming Minotaur",
  "Rock Dwarf",
  "Root Leshy",
  "Running Animal",
  "Runtboss Hobgoblin",
  "Sacred Nagaji",
  "Sailfish Merfolk",
  "Sanctuary Samsaran",
  "Sandstrider Lizardfolk",
  "Scalekeeper Vishkanya",
  "Scavenger Strix",
  "Seaweed Leshy",
  "Seer Elf",
  "Sensate Gnome",
  "Sewer Rat",
  "Shadow of the Courtier",
  "Shadow of the Hermit",
  "Shadow of the Sailor",
  "Shadow of the Smith",
  "Shadow of the Wanderer",
  "Shadow Rat",
  "Shapewrought Fleshwarp",
  "Sharp-Eared Catfolk",
  "Sharpshooter Automaton",
  "Shifting Skeleton",
  "Shimmertongue Nagaji",
  "Shoreline Strix",
  "Shortshanks Hobgoblin",
  "Skilled Human",
  "Skyborn Tengu",
  "Slabsoul Minotaur",
  "Smokeworker Hobgoblin",
  "Snaptongue Tripkee",
  "Snaring Anadi",
  "Snow Goblin",
  "Snow Rat",
  "Songbird Strix",
  "Spellhorn Kobold",
  "Spellkeeper Shisk",
  "Spindly Anadi",
  "Spined Azarketi",
  "Stalker Minotaur",
  "Steadfast Tanuki",
  "Steelskin Hobgoblin",
  "Stickytoe Tripkee",
  "Stonestep Shisk",
  "Stormtossed Tengu",
  "Stoutheart Centaur",
  "Strong Oak",
  "Strong-Blooded Dwarf",
  "Stronggut Shisk",
  "Strongjaw Kobold",
  "Stuffed Poppet",
  "Sturdy Skeleton",
  "Suli",
  "Surgewise Fleshwarp",
  "Sweetbreath Kholo",
  "Swimming Animal",
  "Sylph",
  "Tactile Azarketi",
  "Tailed Goblin",
  "Taloned Tengu",
  "Talos",
  "Technological Fleshwarp",
  "Thalassic Azarketi",
  "Thickcoat Shoony",
  "Thickskin Tripkee",
  "Thorned Rose",
  "Titan Nagaji",
  "Toy Poppet",
  "Treedweller Goblin",
  "Trogloshi",
  "Tsukumogami Poppet",
  "Tunnel Rat",
  "Tunnelflood Kobold",
  "Twilight Halfling",
  "Umbral Gnome",
  "Unbreakable Goblin",
  "Undine",
  "Unseen Lizardfolk",
  "Venom-Resistant Vishkanya",
  "Venomous Anadi",
  "Venomshield Nagaji",
  "Venomtail Kobold",
  "Versatile Human",
  "Vicious Goloma",
  "Vigilant Goloma",
  "Vine Leshy",
  "Virtuous Tanuki",
  "Vivacious Gnome",
  "Wajaghand Vanara",
  "Waning Moon Sarangay",
  "Warden Human (BB)",
  "Warmarch Hobgoblin",
  "Warrenbred Hobgoblin",
  "Warrior Android",
  "Warrior Automaton",
  "Wavediver Tengu",
  "Waxing Moon Sarangay",
  "Wellspring Gnome",
  "Wetlander Lizardfolk",
  "Whipfang Nagaji",
  "Whisper Elf",
  "Wilderness Samsaran",
  "Wildwood Halfling",
  "Windup Poppet",
  "Windweb Tripkee",
  "Winter Catfolk",
  "Winter Kholo",
  "Winter Orc",
  "Wintertouched Human",
  "Wishborn Poppet",
  "Wisp Fetchling",
  "Witch Kholo",
  "Woodland Elf",
  "Woodstalker Lizardfolk",
  "Xyloshi",
] as const
