/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps\web\public\models\D10_3D_Red.glb -o apps\web\src\vtt\dice-roller\models\D10.tsx -t -k 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    d10_1: THREE.Mesh
    d10_2: THREE.Mesh
  }
  materials: {
    Dice: THREE.MeshStandardMaterial
    ['Numbers.001']: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function D10Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/D10_3D_Red.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="d10" position={[0.046, 0.663, -1.445]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh name="d10_1" geometry={nodes.d10_1.geometry} material={materials.Dice} />
        <mesh name="d10_2" geometry={nodes.d10_2.geometry} material={materials['Numbers.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/D10_3D_Red.glb')


