/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps\web\public\models\D12_3D_Red.glb -o apps\web\src\vtt\dice-roller\models\D12.tsx -t -k 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    d12_1: THREE.Mesh
    d12_2: THREE.Mesh
  }
  materials: {
    Dice: THREE.MeshStandardMaterial
    Numbers: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function D12Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/D12_3D_Red.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="d12" position={[-1.545, 0.819, -1.677]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh name="d12_1" geometry={nodes.d12_1.geometry} material={materials.Dice} />
        <mesh name="d12_2" geometry={nodes.d12_2.geometry} material={materials.Numbers} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/D12_3D_Red.glb')


