/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps\web\public\models\D20_3D_Red.glb -o apps\web\src\vtt\dice-roller\models\D20.tsx -t -k 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    d20_1: THREE.Mesh
    d20_2: THREE.Mesh
  }
  materials: {
    Dice: THREE.MeshStandardMaterial
    Numbers: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function D20Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/D20_3D_Red.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="d20" position={[0.405, 0.851, 1.206]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh name="d20_1" geometry={nodes.d20_1.geometry} material={materials.Dice} />
        <mesh name="d20_2" geometry={nodes.d20_2.geometry} material={materials.Numbers} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/D20_3D_Red.glb')


