/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps\web\public\models\D4_3D_Red.glb -o apps\web\src\vtt\dice-roller\models\D4.tsx -t -k 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cone_1: THREE.Mesh
    Cone_2: THREE.Mesh
  }
  materials: {
    Dice: THREE.MeshStandardMaterial
    Numbers: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function D4Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/D4_3D_Red.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="Cone" position={[-0.821, 0.325, 0.172]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh name="Cone_1" geometry={nodes.Cone_1.geometry} material={materials.Dice} />
        <mesh name="Cone_2" geometry={nodes.Cone_2.geometry} material={materials.Numbers} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/D4_3D_Red.glb')


