/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps\web\public\models\D6_3D_Red.glb -o apps\web\src\vtt\dice-roller\models\D6.tsx -t -k 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    d6_1: THREE.Mesh
    d6_2: THREE.Mesh
  }
  materials: {
    Dice: THREE.MeshStandardMaterial
    Numbers: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function D6Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/D6_3D_Red.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="d6" position={[-2.447, 0.746, 0.325]} rotation={[Math.PI / -6, -0.75, -0.3]}>
        <mesh name="d6_1" geometry={nodes.d6_1.geometry} material={materials.Dice} />
        <mesh name="d6_2" geometry={nodes.d6_2.geometry} material={materials.Numbers} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/D6_3D_Red.glb')


