/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 apps\web\public\models\D8_3D_Red.glb -o apps\web\src\vtt\dice-roller\models\D8.tsx -t -k 
*/

import * as THREE from 'three'
import type { JSX } from 'react'
import { useGLTF } from '@react-three/drei'
import type { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    d8_1: THREE.Mesh
    d8_2: THREE.Mesh
  }
  materials: {
    Dice: THREE.MeshStandardMaterial
    Numbers: THREE.MeshStandardMaterial
  }
  animations: unknown[]
}

export function D8Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/D8_3D_Red.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group name="d8" position={[1.524, 0.694, -0.271]} rotation={[Math.PI / 2, 0, 0]}>
        <mesh name="d8_1" geometry={nodes.d8_1.geometry} material={materials.Dice} />
        <mesh name="d8_2" geometry={nodes.d8_2.geometry} material={materials.Numbers} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/D8_3D_Red.glb')


