// Static names extracted from branch development: packages/game-system-pathfinder-2e/src/server/character-options/data/ancestries.generated.ts.
// Keep this file independent from the other PF2e select catalogs.
export const PATHFINDER_2E_ANCESTRIES = [
  "Anadi",
  "Android",
  "Athamaru",
  "Automaton",
  "Awakened Animal",
  "Azarketi",
  "Catfolk",
  "Centaur",
  "Conrasu",
  "Dwarf",
  "Elf",
  "Fetchling",
  "Fleshwarp",
  "Ghoran",
  "Gnome",
  "Goblin",
  "Goloma",
  "Halfling",
  "Hobgoblin",
  "Human",
  "Kashrishi",
  "Kholo",
  "Kitsune",
  "Kobold",
  "Leshy",
  "Lizardfolk",
  "Merfolk",
  "Minotaur",
  "Nagaji",
  "Orc",
  "Poppet",
  "Ratfolk",
  "Samsaran",
  "Sarangay",
  "Shisk",
  "Shoony",
  "Skeleton",
  "Sprite",
  "Strix",
  "Surki",
  "Tanuki",
  "Tengu",
  "Tripkee",
  "Vanara",
  "Vishkanya",
  "Wayang",
  "Yaksha",
  "Yaoguai",
] as const
