import type { Pathfinder2eEffectPtBrTranslation } from './campaign'

export const PATHFINDER_2E_EQUIPMENT_EFFECT_PT_BR_09 = Object.freeze({
  'equipment-effects:zqKzWGLODgIvtiKf': { name: 'Efeito: Lâmina Guardiã de Magias', description: 'Concedido por Lâmina Guardiã de Magias.\n\nVocê recebe +1 de bônus de circunstância em salvamentos contra magias que tenham você como alvo.' },
  'equipment-effects:Zqs1VvRm5Oq7DwX0': { name: 'Efeito: Fraqueza do Anão de Latão', description: 'Concedido pelo Anão de Latão.\n\nVocê recebe fraqueza igual à metade do seu nível ao tipo de energia anterior do Anão de Latão.' },
  'equipment-effects:ZRr3fsaw9676L4JT': { name: 'Efeito: Escama Impenetrável', description: 'Concedido por Escama Impenetrável.\n\nVocê recebe resistência a dano físico igual à quantidade de escamas violetas, até o máximo de 8.' },
  'equipment-effects:ztxW3lBPRcesF7wK': { name: 'Efeito: Mutagênico Cognitivo (Moderado)', description: 'Concedido por Mutagênico Cognitivo (Moderado).\n\nBenefício: você recebe +2 de bônus de item em testes de Arcanismo, Ofício, Saber, Ocultismo e Sociedade e em todos os testes para Recordar Conhecimento. Suas falhas críticas ao Recordar Conhecimento se tornam falhas.\n\nDesvantagem: você sofre –2 de penalidade em rolagens de ataque com armas e desarmados e em testes de Atletismo e Acrobatismo. Você pode carregar 2 Volumes a menos antes de ficar sobrecarregado, e seu Volume máximo é reduzido em 4.' },
  'equipment-effects:ZV9rtVOD1eDTwcY4': { name: 'Efeito: Determinação (Estágio 3)', description: 'Concedido por Determinação.\n\nA criatura sofre –4 de penalidade de item em testes de Percepção.' },
  'equipment-effects:zW8adCNIRo46mfEH': { name: 'Efeito: Elixir Viperino (Maior)', description: 'Concedido por Elixir Viperino (Maior).\n\nVocê recebe um ataque desarmado de presas que causa 1d6 de dano perfurante. Você recebe +3 de bônus de item em rolagens de ataque e dano desarmadas quando Golpeia com suas presas ou outro ataque de mordida.' },
  'equipment-effects:ZxT8Shp8NZaQRjlQ': { name: 'Efeito: Mutagênico Omatofórico', description: 'Concedido por Mutagênico Omatofórico.\n\nBenefício: você recebe visão em todas as direções, +2 de bônus de item em testes visuais de Percepção e visão na penumbra se ainda não a possuir.\n\nDesvantagem: você sofre –2 de penalidade em salvamentos contra efeitos com o traço visual.' },
  'equipment-effects:zY7cemRcFD2zAVbC': { name: 'Efeito: Juramento do Devoto', description: 'Concedido por Juramento do Devoto.\n\nVocê recebe +1 de bônus de estado em salvamentos de Vontade. Escolha uma arma ou um Golpe desarmado; o ataque escolhido causa 1d6 de dano de fogo adicional.' },
  'equipment-effects:zZsdex5orF5Odpus': { name: 'Efeito: Máscara do Encanto', description: 'Concedido por Máscara do Encanto.\n\nVocê recebe +4 de bônus de estado no teste acionador.' },
} satisfies Readonly<Record<string, Pathfinder2eEffectPtBrTranslation>>)
